USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_OLTP_VEICULO(@DATA_CARGA DATETIME)
AS BEGIN
        DELETE FROM TB_AUX_VEICULO WHERE @DATA_CARGA = DATA_CARGA

		INSERT INTO TB_AUX_VEICULO(DATA_CARGA, ID_VEICULO, VEICULO, ID_FABRICANTE, FABRICANTE)
		SELECT @DATA_CARGA, V.COD_VEICULO, V.NOME, F.COD_FABRICANTE,F.NOME
		FROM TB_VEICULO V JOIN TB_FABRICANTE F
		ON(V.COD_VEICULO = F.COD_FABRICANTE)

END

EXEC SP_OLTP_VEICULO'20220101'

SELECT * FROM TB_AUX_VEICULO