USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_OLTP_VENDA(@DATA_CARGA DATETIME)
AS BEGIN
        DELETE FROM TB_AUX_VENDA WHERE @DATA_CARGA = DATA_CARGA

		INSERT INTO TB_AUX_VENDA(DATA_CARGA, DATA_VENDA, ID_LOJA, ID_FUNCIONARIO, ID_VEICULO, ID_TIPO_PAGAMENTO, VALOR)
		SELECT @DATA_CARGA, VD.DATA_VENDA, L.COD_LOJA, F.COD_FUNCIONARIO, V.COD_VEICULO, P.COD_TIPO_PAGAMENTO, VD.VALOR
		FROM TB_VENDA VD JOIN TB_LOJA L 
		ON(VD.COD_LOJA = L.COD_LOJA) JOIN TB_LOJA_TB_FUNCIONARIO F 
		ON(F.COD_LOJA = L.COD_LOJA) JOIN TB_VEICULO V 
		ON(V.COD_LOJA = L.COD_LOJA) JOIN TB_TIPO_PAGAMENTO P 
		ON(P.COD_TIPO_PAGAMENTO = VD.COD_TIPO_PAGAMENTO)
		

END

EXEC SP_OLTP_VENDA '20220101'

SELECT * FROM TB_AUX_VENDA

DROP TABLE TB_AUX_VENDA