USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_OLTP_VENDA(@DATA_CARGA DATETIME)
AS BEGIN
        DELETE FROM TB_AUX_VENDA WHERE @DATA_CARGA = DATA_CARGA

		INSERT INTO TB_AUX_VENDA(DATA_CARGA, DATA_VENDA, ID_LOJA, ID_FUNCIONARIO, ID_VEICULO, ID_TIPO_PAGAMENTO, VALOR)
		SELECT @DATA_CARGA, DATA_VENDA, COD_LOJA, COD_FUNCIONARIO, COD_VEICULO, COD_TIPO_PAGAMENTO, VALOR
		FROM TB_VENDA
END

EXEC SP_OLTP_VENDA '20220102'

SELECT * FROM TB_AUX_VENDA

DROP TABLE TB_AUX_VENDA