-- Scripts ddl para o ambiente dimensional

USE bd_concessionaria


DROP TABLE IF EXISTS FATO_VENDA
DROP TABLE IF EXISTS DIM_VEICULO
DROP TABLE IF EXISTS DIM_LOJA
DROP TABLE IF EXISTS DIM_FUNCIONARIO
DROP TABLE IF EXISTS DIM_FABRICANTE
DROP TABLE IF EXISTS DIM_TEMPO
DROP TABLE IF EXISTS DIM_TIPO_PAGAMENTO

CREATE TABLE DIM_VEICULO (
   ID_DIM_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   ID_VEICULO INT NOT NULL,
   NOME_VEICULO VARCHAR(50) NOT NULL,
   ID_FABRICANTE INT NOT NULL,
   NOME_FABRICANTE VARCHAR(50) NOT NULL
)


CREATE TABLE DIM_LOJA (
	ID_DIM_LOJA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_LOJA INT NOT NULL,
	NOME_LOJA VARCHAR(45) NOT NULL,
	GERENTE VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	ESTADO VARCHAR(45) NOT NULL,
)

CREATE TABLE DIM_FUNCIONARIO (
    ID_DIM_FUNCIONARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_FUNCIONARIO INT NOT NULL,
	NOME_FUNCIONARIO VARCHAR(45) NOT NULL,
	ID_CARGO INT NOT NULL,
	CARGO VARCHAR(45) NOT NULL
)

CREATE TABLE DIM_FABRICANTE (
    ID_DIM_FABRICANTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_FABRICANTE INT NOT NULL,
	NOME_FABRICANTE VARCHAR(45) NOT NULL,
	CNPJ_FABRICANTE VARCHAR(45) NOT NULL,
	ESTADO_FABRICANTE VARCHAR(45) NOT NULL
)

CREATE TABLE DIM_TIPO_PAGAMENTO (
	ID_DIM_TIPO_PAGAMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_TIPO_PAGAMENTO INT NOT NULL,
	TIPO_PAGAMENTO VARCHAR(45)
)


CREATE TABLE DIM_TEMPO (
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(3) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT  NULL,
	DIA_SEMANA VARCHAR(20)  NULL,
	FIM_SEMANA VARCHAR(3)  NULL CHECK (FIM_SEMANA IN ('SIM','NAO')),
	MES INT  NULL,
	NOME_MES VARCHAR(15)  NULL,
	TRIMESTRE INT  NULL,
	NOME_TRIMESTRE VARCHAR(45)  NULL,
	SEMESTRE INT  NULL,
	NOME_SEMESTRE VARCHAR(45)  NULL,
	ANO INT NOT NULL
)

CREATE TABLE FATO_VENDA (
	ID_VENDA BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_FUNCIONARIO INT NOT NULL,
	ID_VEICULO INT NOT NULL,
	--ID_TEMPO BIGINT NULL,
	ID_TIPO_PAGAMENTO INT NOT NULL,
	ID_LOJA INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL DEFAULT (1)

	CONSTRAINT FK_DIM_LOJA FOREIGN KEY (ID_LOJA) REFERENCES DIM_LOJA (ID_DIM_LOJA),
	CONSTRAINT FK_DIM_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES DIM_FUNCIONARIO(ID_DIM_FUNCIONARIO),
	CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_VEICULO) REFERENCES DIM_VEICULO (ID_DIM_VEICULO),
	--CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_DIM_TIPO_PAGAMENTO FOREIGN KEY (ID_TIPO_PAGAMENTO) REFERENCES DIM_TIPO_PAGAMENTO (ID_DIM_TIPO_PAGAMENTO)
)