-- SCRIPTS DDL PARA O AMBIENTE OPERACIONAL

USE bd_concessionaria

DROP TABLE IF EXISTS TB_LOJA
DROP TABLE IF EXISTS TB_CLIENTE
DROP TABLE IF EXISTS TB_VEICULO
DROP TABLE IF EXISTS TB_FABRICANTE
DROP TABLE IF EXISTS TB_FUNCIONARIO
DROP TABLE IF EXISTS TB_CARGO
DROP TABLE IF EXISTS TB_VENDA
DROP TABLE IF EXISTS TB_TIPO_PAGAMENTO
DROP TABLE IF EXISTS TB_ESTADO
DROP TABLE IF EXISTS TB_CIDADE
DROP TABLE IF EXISTS TB_LOJA_TB_FUNCIONARIO

CREATE TABLE TB_LOJA (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Cod_Cidade INT NOT NULL,
	Cod_Gerente INT NOT NULL, 
	TB_CIDADE_id INT NOT NULL
)

INSERT INTO TB_LOJA (NOME,Cod_Cidade,Cod_Gerente)
VALUES ('LOJA EXEMPLO', 1, 1)

CREATE TABLE TB_CLIENTE (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	Telefone VARCHAR(9) NOT NULL,
	Endereco VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	TB_LOJA_Id INT NOT NULL
)

INSERT INTO TB_CLIENTE(NOME,CPF,Telefone,Endereco,Email)
VALUES ('CHARLES', '08254335508', '999082332','RUA SAUDALINA SANTANA FERREIRA', 'charlees.dayan@gmail.com')

CREATE TABLE TB_VEICULO (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(45) NOT NULL,
	AnoFabricacao VARCHAR(10) NOT NULL,
	Modelo VARCHAR(45) NOT NULL,
	Preco NUMERIC(10,2) NOT NULL,
	Placa VARCHAR(10) NOT NULL,
)