-- SCRIPTS DDL PARA O AMBIENTE OPERACIONAL

USE bd_concessionaria

DROP TABLE IF EXISTS TB_LOJA
DROP TABLE IF EXISTS TB_CLIENTE
DROP TABLE IF EXISTS TB_VEICULO
DROP TABLE IF EXISTS TB_FABRICANTE
DROP TABLE IF EXISTS TB_FUNCIONARIO
DROP TABLE IF EXISTS TB_CARGO
DROP TABLE IF EXISTS TB_VENDA
DROP TABLE IF EXISTS TB_TIPO_PAGAMENTO
DROP TABLE IF EXISTS TB_ESTADO
DROP TABLE IF EXISTS TB_CIDADE
DROP TABLE IF EXISTS TB_LOJA_TB_FUNCIONARIO

CREATE TABLE TB_ESTADO (
	COD_ESTADO INT NOT NULL PRIMARY KEY,
	ESTADO VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL
)

INSERT INTO TB_ESTADO VALUES (01, 'ALAGOAS', 'AL')
INSERT INTO TB_ESTADO VALUES (02, 'BAHIA', 'BA')
INSERT INTO TB_ESTADO VALUES (03, 'CEARA', 'CE')
INSERT INTO TB_ESTADO VALUES (04, 'MARANHAO', 'MA')
INSERT INTO TB_ESTADO VALUES (05, 'PARAIBA', 'PB')
INSERT INTO TB_ESTADO VALUES (06, 'PERNAMBUCO', 'PE')
INSERT INTO TB_ESTADO VALUES (07, 'PIAUI', 'PI')
INSERT INTO TB_ESTADO VALUES (08, 'RIO GRANDE DO NORTE', 'RN')
INSERT INTO TB_ESTADO VALUES (09, 'SERGIPE', 'SE')

CREATE TABLE TB_CIDADE (
	COD_CIDADE INT NOT NULL PRIMARY KEY,
	CIDADE VARCHAR(100) NOT NULL,
	COD_ESTADO INT NOT NULL
	CONSTRAINT FK_ESTADO FOREIGN KEY (COD_ESTADO) REFERENCES TB_ESTADO (COD_ESTADO)
)

INSERT INTO TB_CIDADE VALUES (0001, 'MACEIO', 01)
INSERT INTO TB_CIDADE VALUES (0002, 'SALVADOR', 02)
INSERT INTO TB_CIDADE VALUES (0003, 'FORTALEZA', 03)
INSERT INTO TB_CIDADE VALUES (0004, 'SAO LUIS', 04)
INSERT INTO TB_CIDADE VALUES (0005, 'JOAO PESSOA', 05)
INSERT INTO TB_CIDADE VALUES (0006, 'RECIFE', 06)
INSERT INTO TB_CIDADE VALUES (0007, 'TERESINA', 07)
INSERT INTO TB_CIDADE VALUES (0008, 'NATAL', 08)
INSERT INTO TB_CIDADE VALUES (0009, 'ARACAJU', 09)

CREATE TABLE TB_CARGO (
    COD_CARGO INT NOT NULL PRIMARY KEY,
	NM_CARGO VARCHAR(100) NOT NULL
)

CREATE TABLE TB_FUNCIONARIO (
 	COD_FUNCIONARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	COD_CARGO INT NOT NULL
	CONSTRAINT FK_CARGO FOREIGN KEY (COD_CARGO) REFERENCES TB_CARGO (COD_CARGO)
)

CREATE TABLE TB_LOJA (
	COD_LOJA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	LOJA VARCHAR(50) NOT NULL,
	COD_CIDADE INT NOT NULL,
	CONSTRAINT FK_CIDADE FOREIGN KEY (COD_CIDADE) REFERENCES TB_CIDADE (COD_CIDADE),
	COD_GERENTE INT NOT NULL,
	CONSTRAINT FK_GERENTE FOREIGN KEY (COD_GERENTE) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO)
)

CREATE TABLE TB_CLIENTE (
	COD_CLIENTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	TELEFONE VARCHAR(9) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	COD_LOJA INT NOT NULL
	CONSTRAINT FK_LOJA FOREIGN KEY (COD_LOJA) REFERENCES TB_LOJA (COD_LOJA)
)

INSERT INTO TB_CLIENTE(NOME,CPF,TELEFONE,ENDERECO,EMAIL,COD_LOJA)
VALUES ('CHARLES', '08254335508', '999082332','RUA SAUDALINA SANTANA FERREIRA', 'charlees.dayan@gmail.com',1)


CREATE TABLE TB_FABRICANTE (
	COD_FABRICANTE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(45) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL
)
INSERT INTO TB_FABRICANTE VALUES ('CHEVROLET', '68841262000112','SERGIPE')
INSERT INTO TB_FABRICANTE VALUES ('FIAT', '56154215000111', 'BAHIA')
INSERT INTO TB_FABRICANTE VALUES ('WOLKSVAGEN', '55788514000145', 'PARAIBA')

CREATE TABLE TB_VEICULO (
	COD_VEICULO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	ANO_FABRICACAO VARCHAR(10) NOT NULL,
	MODELO VARCHAR(45) NOT NULL,
	PRECO NUMERIC(10,2) NOT NULL,
	PLACA VARCHAR(8),
	COD_FABRICANTE INT NOT NULL
	CONSTRAINT FK_FABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES TB_FABRICANTE (COD_FABRICANTE),
	COD_LOJA INT NOT NULL
	CONSTRAINT FK_LOJA FOREIGN KEY (COD_LOJA) REFERENCES TB_LOJA (COD_LOJA)
)

INSERT INTO TB_VEICULO VALUES ('CORSA', '2005', 'CLASSIC', 20000.00, 'MUE-3429', 1)
INSERT INTO TB_VEICULO VALUES ('ARGO', '2020', 'TRACKER', 70000.00, 'EJE-3926', 2)
INSERT INTO TB_VEICULO VALUES ('GOLF', '2021', 'GTI', 20000.00, 'EUA-6969', 3)

CREATE TABLE TB_LOJA_TB_FUNCIONARIO (
	COD_LOJA INT NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	PRIMARY KEY (COD_LOJA, COD_FUNCIONARIO),
	CONSTRAINT FK_LOJA_FUNC_LOJA FOREIGN KEY (COD_LOJA) REFERENCES TB_LOJA (COD_LOJA),
	CONSTRAINT FK_LOJA_FUNC_FUNC FOREIGN KEY (COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO)
)

CREATE TABLE TB_TIPO_PAGAMENTO (
	COD_TIPO_PAGAMENTO INT NOT NULL PRIMARY KEY,
	TIPO_PAGAMENTO VARCHAR(100) NOT NULL
)

INSERT INTO TB_TIPO_PAGAMENTO VALUES (1, 'A VISTA')
INSERT INTO TB_TIPO_PAGAMENTO VALUES (2, 'CARTAO')
INSERT INTO TB_TIPO_PAGAMENTO VALUES (3, 'VIA PIX')

CREATE TABLE TB_VENDA (
	COD_VENDA BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DATA_VENDA DATETIME NOT NULL,
	VALOR NUMERIC(10,2),
	COD_LOJA INT NOT NULL,
	COD_TIPO_PAGAMENTO INT NOT NULL,
	COD_VEICULO INT NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	CONSTRAINT FK_LOJA FOREIGN KEY (COD_LOJA) REFERENCES TB_LOJA (COD_LOJA),
	CONSTRAINT FK_TIPO_PAGAMENTO FOREIGN KEY (COD_TIPO_PAGAMENTO) REFERENCES TB_TIPO_PAGAMENTO (COD_TIPO_PAGAMENTO),
	CONSTRAINT FK_VEICULO FOREIGN KEY (COD_VEICULO) REFERENCES TB_VEICULO (COD_VEICULO),
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(COD_FUNCIONARIO)
)

SELECT * FROM TB_CIDADE
SELECT * FROM TB_ESTADO
SELECT * FROM TB_FABRICANTE
SELECT * FROM TB_CLIENTE
SELECT * FROM TB_VEICULO