USE bd_concessionaria

--- QUANTIDADE DE VENDAS POR VEICULO
SELECT VE.NOME_VEICULO, ISNULL(SUM(V.QUANTIDADE),0) 'TOTAL VENDIDOS'
FROM FATO_VENDA V
RIGHT JOIN DIM_VEICULO VE
ON(V.ID_VEICULO = VE.ID_DIM_VEICULO)
GROUP BY VE.NOME_VEICULO

--- QUANTIDADE DE VENDAS POR FUNCIONARIO
SELECT F.NOME_FUNCIONARIO, ISNULL(SUM(V.QUANTIDADE),0) 'QUANTIDADE DE VENDAS'
FROM FATO_VENDA V
RIGHT JOIN DIM_FUNCIONARIO F
ON(V.ID_FUNCIONARIO = F.ID_DIM_FUNCIONARIO)
GROUP BY F.NOME_FUNCIONARIO

--- QUANTIDADE DE VENDAS POR FABRICANTE
SELECT F.NOME_FABRICANTE, ISNULL(SUM(V.QUANTIDADE),0) 'QUANTIDADE DE VENDAS'
FROM FATO_VENDA V
RIGHT JOIN DIM_VEICULO VE
ON(V.ID_VEICULO = VE.ID_DIM_VEICULO) JOIN DIM_FABRICANTE F
ON(VE.ID_FABRICANTE = F.ID_DIM_FABRICANTE)
GROUP BY F.NOME_FABRICANTE

--- QUANTIDADE DE VENDAS POR TIPO DE PAGAMENTO
SELECT T.TIPO_PAGAMENTO, ISNULL(SUM(V.QUANTIDADE),0) 'QUANTIDADE DE VENDAS'
FROM FATO_VENDA V
RIGHT JOIN DIM_TIPO_PAGAMENTO T
ON(V.ID_VEICULO = T.ID_DIM_TIPO_PAGAMENTO)
GROUP BY T.TIPO_PAGAMENTO

/*
--- QUANTIDADE DE VENDAS POR FABRICANTE
SELECT F.NOME_FABRICANTE, ISNULL(SUM(V.QUANTIDADE),0) 'QUANTIDADE DE VENDAS'
FROM FATO_VENDA V
RIGHT JOIN DIM_VEICULO VE
ON(V.ID_VEICULO = VE.ID_DIM_VEICULO) JOIN DIM_FABRICANTE F
ON(VE.ID_FABRICANTE = F.ID_DIM_FABRICANTE) JOIN DIM_TEMPO T 
ON(V.ID_TEMPO = T.ID_TEMPO)
WHERE T.SEMESTRE = 2
GROUP BY F.NOME_FABRICANTE
*/