USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_DIM_LOJA
AS BEGIN
        INSERT INTO DIM_LOJA(ID_LOJA, NOME_LOJA, GERENTE, CIDADE, ESTADO)
		SELECT ID_LOJA, LOJA, GERENTE, CIDADE, ESTADO
		FROM TB_AUX_LOJA
END

EXEC SP_DIM_LOJA

SELECT * FROM DIM_LOJA