USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_DIM_FABRICANTE
AS BEGIN
        INSERT INTO DIM_FABRICANTE(ID_FABRICANTE, NOME_FABRICANTE, CNPJ_FABRICANTE, ESTADO_FABRICANTE)
		SELECT ID_FABRICANTE, NOME, CNPJ, ESTADO
		FROM TB_AUX_FABRICANTE
END

EXEC SP_DIM_FABRICANTE

SELECT * FROM DIM_FABRICANTE