USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_DIM_VEICULO
AS BEGIN
        INSERT INTO DIM_VEICULO(ID_VEICULO, NOME_VEICULO, ID_FABRICANTE, NOME_FABRICANTE)
		SELECT ID_VEICULO, VEICULO, ID_FABRICANTE, FABRICANTE
		FROM TB_AUX_VEICULO
END

EXEC SP_DIM_VEICULO

SELECT * FROM DIM_VEICULO