USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_FATO_VENDA
AS BEGIN
    DECLARE	@ID_FABRICANTE INT, @ID_FUNCIONARIO INT, 
			@ID_VEICULO INT, @ID_TIPO_PAGAMENTO INT,
			@ID_TEMPO INT, @ID_LOJA INT,
			@COD_VENDA INT, @VALOR DECIMAL(10,2), 
			@QUANTIDADE INT, @DATA_CARGA DATETIME,
			@ANO INT, @SEMESTRE INT,
			@DATA_VENDA DATETIME

	DECLARE CURSOR_VENDA CURSOR FOR
	SELECT DATA_CARGA,DATA_VENDA, ID_LOJA, ID_FUNCIONARIO, ID_VEICULO, ID_TIPO_PAGAMENTO, VALOR
	FROM TB_AUX_VENDA

	OPEN CURSOR_VENDA
	FETCH CURSOR_VENDA INTO @DATA_CARGA, @DATA_VENDA, @ID_LOJA, @ID_FUNCIONARIO, @ID_VEICULO, @ID_TIPO_PAGAMENTO, @VALOR

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		--SET @ID_VEICULO = (SELECT ID_VEICULO FROM DIM_VEICULO WHERE ID_VEICULO = @ID_VEICULO)
															
		IF (@ID_VEICULO IS NOT NULL) 
			BEGIN
				
				INSERT INTO FATO_VENDA(ID_FUNCIONARIO, ID_VEICULO, ID_TIPO_PAGAMENTO, ID_LOJA, VALOR, QUANTIDADE)
				VALUES	(@ID_FUNCIONARIO, @ID_VEICULO, @ID_TIPO_PAGAMENTO, @ID_LOJA, @VALOR, 1)
			END

		FETCH CURSOR_VENDA INTO @DATA_CARGA, @DATA_VENDA, @ID_LOJA, @ID_FUNCIONARIO, @ID_VEICULO, @ID_TIPO_PAGAMENTO, @VALOR
	END
	CLOSE CURSOR_VENDA
	DEALLOCATE CURSOR_VENDA
END

EXEC SP_FATO_VENDA

SELECT * FROM TB_AUX_VENDA

SELECT * FROM FATO_VENDA