USE bd_concessionaria

CREATE OR ALTER PROCEDURE SP_FATO_VENDA
AS BEGIN
    DECLARE	@ID_FABRICANTE INT, @ID_FUNCIONARIO INT, 
			@ID_VEICULO INT, @ID_TIPO_PAGAMENTO INT,
			@ID_TEMPO INT, @ID_LOJA INT,
			@COD_VENDA INT, @VALOR DECIMAL(10,2), 
			@QUANTIDADE INT, @DATA_CARGA DATETIME,
			@ANO INT, @SEMESTRE INT,
			@DATA_VENDA DATETIME

	DECLARE CURSOR_VENDA CURSOR FOR
	SELECT DATA_VENDA, ID_LOJA, ID_FUNCIONARIO, ID_VEICULO, ID_TIPO_PAGAMENTO, VALOR
	FROM TB_AUX_VENDA

	OPEN CURSOR_VENDA
	FETCH CURSOR_VENDA INTO @DATA_VENDA, @ID_LOJA, @ID_FUNCIONARIO, @ID_VEICULO, @ID_TIPO_PAGAMENTO, @VALOR

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SET @QUANTIDADE = 1
		SET @ID_TEMPO = 123
		--(SELECT ANO, SEMESTRE FROM DIM_TEMPO T WHERE T.ANO = @ANO AND T.SEMESTRE = @SEMESTRE)
		
		IF (@ID_FABRICANTE IS NOT NULL AND
			@ID_FUNCIONARIO IS NOT NULL AND 
			@ID_VEICULO IS NOT NULL AND 
			@ID_TEMPO IS NOT NULL AND 
			@ID_TIPO_PAGAMENTO IS NOT NULL AND 
			@ID_LOJA IS NOT NULL AND 
			@COD_VENDA IS NOT NULL AND 
			@VALOR IS NOT NULL AND 
			@QUANTIDADE IS NOT NULL)
			BEGIN
				INSERT INTO FATO_VENDA(ID_FABRICANTE, ID_FUNCIONARIO, ID_VEICULO, ID_TEMPO, ID_TIPO_PAGAMENTO, ID_LOJA, COD_VENDA, VALOR, QUANTIDADE)
				VALUES	(@ID_FABRICANTE, @ID_FUNCIONARIO, @ID_VEICULO, @ID_TEMPO, @ID_TIPO_PAGAMENTO, @ID_LOJA, @COD_VENDA, @VALOR, @QUANTIDADE)
				SELECT * FROM TB_AUX_VENDA
			END

		FETCH CURSOR_VENDA INTO @DATA_VENDA, @ID_LOJA, @ID_FUNCIONARIO, @ID_VEICULO, @ID_TIPO_PAGAMENTO, @VALOR
	END
	CLOSE CURSOR_VENDA
	DEALLOCATE CURSOR_VENDA
END

EXEC SP_FATO_VENDA

SELECT * FROM TB_AUX_VENDA

SELECT * FROM FATO_VENDA